arifszn/gitprofile

README.md
- Please check if the formatting is acceptable 
- Please check if the removal of npm deploy is acceptable. (It's better to remove technical stuff in a package like this to make it more user friendly)
Ideally what the readme should do is say, Fork the repo. And make a release with your updated config.js and done.
=> Updated Readme on how to use continuous deployment

.github/workflows/CI-CD.yml
-Updated Node setup to v2
-Removed manual caching with setup actions. It's managed by a separate action
=> Updated CI Config

README.md, package-lock.json, package.json, src/config.js, src/helpers/setupHotjar.js, src/index.js
This PR adds hotjar support for this repo. Hope you like it.
=> feat(all): add hotjar

.github/workflows/deploy.yml
=> build: change deploy folder for CI/CD

vite.config.js
=> build: define `base` in vite.config.js

.github/workflows/test-deploy.yml
=> build: create CI/CD for test deployment

.github/workflows/lint.yml
=> Create CI/CD for automated lint and prettier checking

src/helpers/utils.jsx
=> feat: check the value of `localStorage.getItem` exists in the theme array

src/components/blog/index.jsx, src/components/project/index.jsx, src/gitprofile.config.js
=> feat: make the project and blog items openable on right click action

README.md, package.json, vite.config.js
=> Update deploy guide

README.md, gitprofile.config.js
=> feat: add control to customize the button style on custom theme

package-lock.json, package.json, src/components/education/index.jsx, src/components/experience/index.jsx
=> feat: make experience and education sections more visible

package-lock.json, package.json, src/main.jsx
=> build: update to react 18

package-lock.json, package.json, src/components/blog/index.jsx, src/components/project/index.jsx
=> feat: display empty blog state

README.md, gitprofile.config.js, src/components/details/index.jsx
=> docs: update installation guide

.github/workflows/deploy.yml, README.md, gitprofile.config.js
=> build: apply explicit permissions

src/helpers/utils.jsx
utils.jsx is now more readable
=> Code Cleanup & Making code more readable

src/helpers/utils.jsx
=> Fix incorrect social link in `sanitizeConfig`

src/components/GitProfile.jsx
=> Add skeleton loader in footer

src/components/avatar-card/index.jsx, src/components/blog/index.jsx, src/components/education/index.jsx, src/components/experience/index.jsx, src/components/project/index.jsx, src/components/skill/index.jsx, src/components/theme-changer/index.jsx
=> Better dark mode support

src/components/details/index.jsx
=> Trim company name in details section

.github/workflows/deploy.yml, README.md
=> Deploy with custom GitHub Actions workflow

LICENSE, README.md, package-lock.json, package.json, src/components/GitProfile.jsx
=> Add MIT License

README.md, gitprofile.config.js, src/components/GitProfile.jsx, src/components/avatar-card/index.jsx, src/helpers/utils.jsx, types/index.d.ts
=> Control avatar ring visibility

README.md
=> Add guide for setting up locally

src/components/avatar-card/index.jsx
=> Add loading indicator for Download Resume button

README.md, gitprofile.config.js, src/components/experience/index.jsx, types/index.d.ts
Hi @arifszn 
Description:
Experience section's company name clickable added to redirect to company page is it has in new tab
Please add `hacktoberfest-accepted` label 
Issue: #195 
Checklist:
1. readme updated
2. Link made optional
3. updated props
4. updated types/index.d.ts
=> Experience company link added

.github/workflows/deploy.yml
=> Upgrade `actions/configure-pages` to v2

gitprofile.config.js, src/components/GitProfile.jsx, src/components/blog/index.jsx, src/components/project/index.jsx
=> Tweak background color

src/components/GitProfile.jsx, src/components/project/index.jsx
resolves issue #218  ![image](https://user-images.githubusercontent.com/19191940/197757451-d67b624c-4b14-4a93-b25d-d2eccaa3f4c1.png)
NOTE: Though i think it would be better to inform the user that there are no public repos i think
=> Hide project section if no public github repo available for user

README.md, gitprofile.config.js, src/components/GitProfile.jsx, src/components/details/index.jsx, src/helpers/utils.jsx, types/index.d.ts
=> Allow users to link their Stack Overflow profile #226

README.md, gitprofile.config.js, package-lock.json, package.json, src/components/GitProfile.jsx, src/components/external-project/index.jsx, src/components/project/index.jsx, src/components/showcase/index.jsx, src/helpers/utils.jsx, types/index.d.ts
Extension of #194.
Close #182.
=> Showcase external projects

README.md, gitprofile.config.js, package.json, src/components/GitProfile.jsx, src/components/footer/index.jsx, src/helpers/utils.jsx
Added an option in config file.
Added a component which renders the custom footer or a default footer if no custom footer is defined.
Updated readme file with related instructions.
Updated version to 2.2.2
Closes #207
=> Add option to display footer

src/components/details/index.jsx, src/components/project/index.jsx
=> Truncate long text

package-lock.json, package.json
=> Update `@arifszn/blog-js` to 2.0.4

src/components/project/index.jsx
Removed a class which are using in Project index fie at line number 92
I tryed to resolved an open error #351 Suggestion - remove capitalizing github projects. 
I think it is resolved. Please take a review on it.
=> Removed Capitalizing githib project #351

README.md, package-lock.json, package.json, vite.config.js
=> Install as Progressive Web App

README.md, gitprofile.config.js, src/components/GitProfile.jsx, src/components/details/index.jsx, src/helpers/utils.jsx, types/index.d.ts
=> Add YouTube as social link

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml
=> Update node version from 16 to 20 in `actions/setup-node`

src/components/external-project-card/index.tsx, src/components/publication-card/index.tsx
=> Justify text alignment of card description

README.md, gitprofile.config.ts, global.d.ts, src/components/details-card/index.tsx, src/interfaces/sanitized-config.tsx, src/utils/index.tsx
Passed the linter check and working as expected locally. Also, there are some minor Readme Changes and code clean-ups
=> Add social links - Reddit, Threads, Udemy

src/constants/errors.tsx
- fixed minor typo in generic error
=> Fix Generic Error's Title

.idx/dev.nix, index.html
=> Add support for Project IDX

src/components/details-card/index.tsx
Fix for multiple organizations
=> Handle multiple organizations

README.md
When we tryto deploy this on Vercel with the default configuration, you will be left with a blank page.  So, the fix for that is to set the `base` to `/`.
=> Documenting the Vercel deployment issure - Black Page
